import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/feed');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).click();
  await page.getByRole('textbox', { name: 'Email Address *' }).fill('admin@gmail.com');
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('admin1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Users' }).click();
  await page.getByRole('row', { name: 'Dushan Perera dushan@gmail.' }).getByRole('combobox').selectOption('Organizer');
  await page.getByRole('row', { name: 'Dushan Perera dushan@gmail.' }).getByRole('combobox').selectOption('Admin');
  await page.getByRole('row', { name: 'Dushan Perera dushan@gmail.' }).getByRole('combobox').selectOption('Student');
  await page.getByRole('button', { name: 'View Organized Events' }).first().click();
  await page.getByRole('button', { name: 'View Organized Events' }).nth(1).click();
  await page.getByRole('row', { name: 'S Supun Perera supun@gmail.' }).getByRole('combobox').selectOption('Organizer');
  await page.getByRole('button', { name: 'View Organized Events' }).nth(1).click();
  await page.getByRole('button', { name: 'View Organized Events' }).nth(1).click();
  await page.getByRole('row', { name: 'S Supun Perera supun@gmail.' }).getByRole('combobox').selectOption('Student');
  await page.getByRole('row', { name: 'C Chanith chanith@gmail.com' }).getByRole('combobox').selectOption('Organizer');
  await page.getByRole('link', { name: 'Events', exact: true }).click();
  await page.getByRole('button', { name: 'Upcoming' }).click();
  await page.getByRole('button', { name: 'Past' }).click();
  await page.getByRole('link', { name: 'General Info' }).click();
  await page.getByRole('button', { name: 'Enable edit profile' }).click();
  await page.getByRole('textbox', { name: 'e.g. Jane Doe' }).click();
  await page.getByRole('textbox', { name: 'e.g. Jane Doe' }).fill('System Admin');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Notifications' }).click();
  await page.getByRole('link', { name: 'Events', exact: true }).click();
  await page.getByRole('button', { name: 'Request Edit' }).first().click();
  await page.getByRole('textbox', { name: 'Enter your reason (optional)' }).click();
  await page.getByRole('textbox', { name: 'Enter your reason (optional)' }).fill('This event should be edited');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Send Request' }).click();
  await page.getByRole('button', { name: 'Request Delete' }).first().click();
  await page.getByRole('textbox', { name: 'Enter your reason (optional)' }).click();
  await page.getByRole('textbox', { name: 'Enter your reason (optional)' }).fill('This event should be deleted');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Send Request' }).click();
  await page.getByRole('link', { name: 'Personal Security' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Total Organizers' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByRole('link', { name: 'Total Events' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Dashboard' }).click();
  await page.getByText('A', { exact: true }).click();
  await page.getByRole('button', { name: 'Logout' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.goto('http://localhost:5173/login');
});